bigodon_agendamento:
    resource: "@BigodonBundle/Controller/AgendamentoController.php"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

bigodon:
    resource: "@BigodonBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
